# No window decorations (removes the "normal" top bar)
no-border

# Start in the center of the screen
geometry=50%:50%

# High-quality rendering
profile=gpu-hq

# Use your Gothic font for the on-screen display (volume, time)
osd-font='Cormorant Garamond'
osd-font-size=30
osd-color='#8b0000' # Wine Red
osd-border-color='#000000' # Black outline
